// Dictionnaire du jeu : liste de PAIRES { theme, difficulte, civil, imposteur }.
// Regle de conception : le mot imposteur est un "cousin" du mot civil —
// meme categorie, attributs communs (pour pouvoir bluffer), mais une
// difference reperable. Ni jumeaux (indemasquables), ni etrangers (grilles).
//
// 200 paires, ~12 themes, repartition difficulte ~40% facile / 40% moyen / 20% difficile.

export const THEMES = [
  "Animaux",
  "Nourriture",
  "Boissons",
  "Fruits & Légumes",
  "Lieux",
  "Métiers",
  "Sport",
  "Objets",
  "Nature",
  "Transports",
  "Vêtements",
  "Loisirs",
];

export const DIFFICULTES = ["facile", "moyen", "difficile"];

export const WORD_PAIRS = [
  // ================= ANIMAUX =================
  { theme: "Animaux", difficulte: "facile", civil: "Chien", imposteur: "Poisson" },
  { theme: "Animaux", difficulte: "facile", civil: "Vache", imposteur: "Aigle" },
  { theme: "Animaux", difficulte: "facile", civil: "Lapin", imposteur: "Requin" },
  { theme: "Animaux", difficulte: "facile", civil: "Souris", imposteur: "Cheval" },
  { theme: "Animaux", difficulte: "facile", civil: "Poule", imposteur: "Serpent" },
  { theme: "Animaux", difficulte: "facile", civil: "Mouton", imposteur: "Dauphin" },
  { theme: "Animaux", difficulte: "facile", civil: "Cochon", imposteur: "Hibou" },
  { theme: "Animaux", difficulte: "facile", civil: "Chèvre", imposteur: "Baleine" },
  { theme: "Animaux", difficulte: "moyen", civil: "Chat", imposteur: "Tigre" },
  { theme: "Animaux", difficulte: "moyen", civil: "Loup", imposteur: "Renard" },
  { theme: "Animaux", difficulte: "moyen", civil: "Cheval", imposteur: "Âne" },
  { theme: "Animaux", difficulte: "moyen", civil: "Lion", imposteur: "Panthère" },
  { theme: "Animaux", difficulte: "moyen", civil: "Abeille", imposteur: "Guêpe" },
  { theme: "Animaux", difficulte: "moyen", civil: "Canard", imposteur: "Oie" },
  { theme: "Animaux", difficulte: "moyen", civil: "Papillon", imposteur: "Libellule" },
  { theme: "Animaux", difficulte: "moyen", civil: "Écureuil", imposteur: "Hamster" },
  { theme: "Animaux", difficulte: "difficile", civil: "Léopard", imposteur: "Guépard" },
  { theme: "Animaux", difficulte: "difficile", civil: "Alligator", imposteur: "Crocodile" },
  { theme: "Animaux", difficulte: "difficile", civil: "Grenouille", imposteur: "Crapaud" },
  { theme: "Animaux", difficulte: "difficile", civil: "Corbeau", imposteur: "Corneille" },

  // ================= NOURRITURE =================
  { theme: "Nourriture", difficulte: "facile", civil: "Pizza", imposteur: "Soupe" },
  { theme: "Nourriture", difficulte: "facile", civil: "Frites", imposteur: "Yaourt" },
  { theme: "Nourriture", difficulte: "facile", civil: "Steak", imposteur: "Salade" },
  { theme: "Nourriture", difficulte: "facile", civil: "Omelette", imposteur: "Tarte" },
  { theme: "Nourriture", difficulte: "facile", civil: "Kebab", imposteur: "Sushi" },
  { theme: "Nourriture", difficulte: "facile", civil: "Lasagnes", imposteur: "Couscous" },
  { theme: "Nourriture", difficulte: "facile", civil: "Sandwich", imposteur: "Gâteau" },
  { theme: "Nourriture", difficulte: "moyen", civil: "Burger", imposteur: "Hot-dog" },
  { theme: "Nourriture", difficulte: "moyen", civil: "Pâtes", imposteur: "Riz" },
  { theme: "Nourriture", difficulte: "moyen", civil: "Crêpe", imposteur: "Gaufre" },
  { theme: "Nourriture", difficulte: "moyen", civil: "Croissant", imposteur: "Brioche" },
  { theme: "Nourriture", difficulte: "moyen", civil: "Quiche", imposteur: "Tarte" },
  { theme: "Nourriture", difficulte: "moyen", civil: "Ravioli", imposteur: "Gnocchi" },
  { theme: "Nourriture", difficulte: "moyen", civil: "Purée", imposteur: "Gratin" },
  { theme: "Nourriture", difficulte: "difficile", civil: "Éclair", imposteur: "Religieuse" },
  { theme: "Nourriture", difficulte: "difficile", civil: "Macaron", imposteur: "Meringue" },
  { theme: "Nourriture", difficulte: "difficile", civil: "Flan", imposteur: "Crème brûlée" },
  { theme: "Nourriture", difficulte: "difficile", civil: "Cannelloni", imposteur: "Lasagnes" },

  // ================= BOISSONS =================
  { theme: "Boissons", difficulte: "facile", civil: "Eau", imposteur: "Bière" },
  { theme: "Boissons", difficulte: "facile", civil: "Lait", imposteur: "Vin" },
  { theme: "Boissons", difficulte: "facile", civil: "Limonade", imposteur: "Whisky" },
  { theme: "Boissons", difficulte: "facile", civil: "Chocolat chaud", imposteur: "Cidre" },
  { theme: "Boissons", difficulte: "facile", civil: "Smoothie", imposteur: "Punch" },
  { theme: "Boissons", difficulte: "moyen", civil: "Café", imposteur: "Thé" },
  { theme: "Boissons", difficulte: "moyen", civil: "Jus", imposteur: "Soda" },
  { theme: "Boissons", difficulte: "moyen", civil: "Vin", imposteur: "Champagne" },
  { theme: "Boissons", difficulte: "moyen", civil: "Bière", imposteur: "Cidre" },
  { theme: "Boissons", difficulte: "moyen", civil: "Thé", imposteur: "Infusion" },
  { theme: "Boissons", difficulte: "moyen", civil: "Coca", imposteur: "Limonade" },
  { theme: "Boissons", difficulte: "difficile", civil: "Cappuccino", imposteur: "Latte" },
  { theme: "Boissons", difficulte: "difficile", civil: "Espresso", imposteur: "Ristretto" },
  { theme: "Boissons", difficulte: "difficile", civil: "Whisky", imposteur: "Cognac" },

  // ================= FRUITS & LÉGUMES =================
  { theme: "Fruits & Légumes", difficulte: "facile", civil: "Pomme", imposteur: "Poireau" },
  { theme: "Fruits & Légumes", difficulte: "facile", civil: "Banane", imposteur: "Carotte" },
  { theme: "Fruits & Légumes", difficulte: "facile", civil: "Fraise", imposteur: "Épinard" },
  { theme: "Fruits & Légumes", difficulte: "facile", civil: "Raisin", imposteur: "Brocoli" },
  { theme: "Fruits & Légumes", difficulte: "facile", civil: "Cerise", imposteur: "Aubergine" },
  { theme: "Fruits & Légumes", difficulte: "facile", civil: "Ananas", imposteur: "Champignon" },
  { theme: "Fruits & Légumes", difficulte: "moyen", civil: "Orange", imposteur: "Mandarine" },
  { theme: "Fruits & Légumes", difficulte: "moyen", civil: "Myrtille", imposteur: "Mûre" },
  { theme: "Fruits & Légumes", difficulte: "moyen", civil: "Carotte", imposteur: "Panais" },
  { theme: "Fruits & Légumes", difficulte: "moyen", civil: "Tomate", imposteur: "Poivron" },
  { theme: "Fruits & Légumes", difficulte: "moyen", civil: "Pêche", imposteur: "Nectarine" },
  { theme: "Fruits & Légumes", difficulte: "moyen", civil: "Melon", imposteur: "Pastèque" },
  { theme: "Fruits & Légumes", difficulte: "difficile", civil: "Citron", imposteur: "Citron vert" },
  { theme: "Fruits & Légumes", difficulte: "difficile", civil: "Courgette", imposteur: "Concombre" },
  { theme: "Fruits & Légumes", difficulte: "difficile", civil: "Clémentine", imposteur: "Mandarine" },
  { theme: "Fruits & Légumes", difficulte: "difficile", civil: "Prune", imposteur: "Pruneau" },

  // ================= LIEUX =================
  { theme: "Lieux", difficulte: "facile", civil: "Plage", imposteur: "Montagne" },
  { theme: "Lieux", difficulte: "facile", civil: "École", imposteur: "Hôpital" },
  { theme: "Lieux", difficulte: "facile", civil: "Cinéma", imposteur: "Piscine" },
  { theme: "Lieux", difficulte: "facile", civil: "Bibliothèque", imposteur: "Stade" },
  { theme: "Lieux", difficulte: "facile", civil: "Aéroport", imposteur: "Ferme" },
  { theme: "Lieux", difficulte: "facile", civil: "Musée", imposteur: "Marché" },
  { theme: "Lieux", difficulte: "facile", civil: "Prison", imposteur: "Parc" },
  { theme: "Lieux", difficulte: "moyen", civil: "Plage", imposteur: "Désert" },
  { theme: "Lieux", difficulte: "moyen", civil: "Forêt", imposteur: "Jungle" },
  { theme: "Lieux", difficulte: "moyen", civil: "Restaurant", imposteur: "Cantine" },
  { theme: "Lieux", difficulte: "moyen", civil: "Hôtel", imposteur: "Auberge" },
  { theme: "Lieux", difficulte: "moyen", civil: "Château", imposteur: "Palais" },
  { theme: "Lieux", difficulte: "moyen", civil: "Bureau", imposteur: "Usine" },
  { theme: "Lieux", difficulte: "moyen", civil: "Village", imposteur: "Ville" },
  { theme: "Lieux", difficulte: "difficile", civil: "Mer", imposteur: "Océan" },
  { theme: "Lieux", difficulte: "difficile", civil: "Ruelle", imposteur: "Avenue" },
  { theme: "Lieux", difficulte: "difficile", civil: "Bistrot", imposteur: "Brasserie" },
  { theme: "Lieux", difficulte: "difficile", civil: "Chalet", imposteur: "Cabane" },

  // ================= MÉTIERS =================
  { theme: "Métiers", difficulte: "facile", civil: "Médecin", imposteur: "Boulanger" },
  { theme: "Métiers", difficulte: "facile", civil: "Pilote", imposteur: "Jardinier" },
  { theme: "Métiers", difficulte: "facile", civil: "Cuisinier", imposteur: "Astronaute" },
  { theme: "Métiers", difficulte: "facile", civil: "Professeur", imposteur: "Plombier" },
  { theme: "Métiers", difficulte: "facile", civil: "Pompier", imposteur: "Coiffeur" },
  { theme: "Métiers", difficulte: "facile", civil: "Facteur", imposteur: "Chirurgien" },
  { theme: "Métiers", difficulte: "moyen", civil: "Policier", imposteur: "Gendarme" },
  { theme: "Métiers", difficulte: "moyen", civil: "Professeur", imposteur: "Formateur" },
  { theme: "Métiers", difficulte: "moyen", civil: "Serveur", imposteur: "Barman" },
  { theme: "Métiers", difficulte: "moyen", civil: "Boulanger", imposteur: "Pâtissier" },
  { theme: "Métiers", difficulte: "moyen", civil: "Peintre", imposteur: "Sculpteur" },
  { theme: "Métiers", difficulte: "moyen", civil: "Infirmier", imposteur: "Aide-soignant" },
  { theme: "Métiers", difficulte: "moyen", civil: "Chanteur", imposteur: "Musicien" },
  { theme: "Métiers", difficulte: "difficile", civil: "Avocat", imposteur: "Notaire" },
  { theme: "Métiers", difficulte: "difficile", civil: "Kinésithérapeute", imposteur: "Ostéopathe" },
  { theme: "Métiers", difficulte: "difficile", civil: "Journaliste", imposteur: "Rédacteur" },

  // ================= SPORT =================
  { theme: "Sport", difficulte: "facile", civil: "Football", imposteur: "Natation" },
  { theme: "Sport", difficulte: "facile", civil: "Boxe", imposteur: "Golf" },
  { theme: "Sport", difficulte: "facile", civil: "Basket", imposteur: "Cyclisme" },
  { theme: "Sport", difficulte: "facile", civil: "Escrime", imposteur: "Marathon" },
  { theme: "Sport", difficulte: "facile", civil: "Équitation", imposteur: "Plongée" },
  { theme: "Sport", difficulte: "facile", civil: "Handball", imposteur: "Ski" },
  { theme: "Sport", difficulte: "moyen", civil: "Tennis", imposteur: "Badminton" },
  { theme: "Sport", difficulte: "moyen", civil: "Ski", imposteur: "Snowboard" },
  { theme: "Sport", difficulte: "moyen", civil: "Volley", imposteur: "Handball" },
  { theme: "Sport", difficulte: "moyen", civil: "Judo", imposteur: "Karaté" },
  { theme: "Sport", difficulte: "moyen", civil: "Course", imposteur: "Marche" },
  { theme: "Sport", difficulte: "moyen", civil: "Natation", imposteur: "Plongeon" },
  { theme: "Sport", difficulte: "moyen", civil: "Aviron", imposteur: "Kayak" },
  { theme: "Sport", difficulte: "difficile", civil: "Rugby", imposteur: "Football américain" },
  { theme: "Sport", difficulte: "difficile", civil: "Patinage", imposteur: "Roller" },
  { theme: "Sport", difficulte: "difficile", civil: "Water-polo", imposteur: "Natation synchronisée" },

  // ================= OBJETS =================
  { theme: "Objets", difficulte: "facile", civil: "Chaise", imposteur: "Lampe" },
  { theme: "Objets", difficulte: "facile", civil: "Livre", imposteur: "Marteau" },
  { theme: "Objets", difficulte: "facile", civil: "Parapluie", imposteur: "Bougie" },
  { theme: "Objets", difficulte: "facile", civil: "Miroir", imposteur: "Ballon" },
  { theme: "Objets", difficulte: "facile", civil: "Clé", imposteur: "Horloge" },
  { theme: "Objets", difficulte: "facile", civil: "Ciseaux", imposteur: "Coussin" },
  { theme: "Objets", difficulte: "facile", civil: "Balai", imposteur: "Téléphone" },
  { theme: "Objets", difficulte: "moyen", civil: "Téléphone", imposteur: "Tablette" },
  { theme: "Objets", difficulte: "moyen", civil: "Fourchette", imposteur: "Cuillère" },
  { theme: "Objets", difficulte: "moyen", civil: "Verre", imposteur: "Tasse" },
  { theme: "Objets", difficulte: "moyen", civil: "Crayon", imposteur: "Stylo" },
  { theme: "Objets", difficulte: "moyen", civil: "Sac", imposteur: "Valise" },
  { theme: "Objets", difficulte: "moyen", civil: "Fauteuil", imposteur: "Canapé" },
  { theme: "Objets", difficulte: "moyen", civil: "Casserole", imposteur: "Poêle" },
  { theme: "Objets", difficulte: "difficile", civil: "Assiette", imposteur: "Soucoupe" },
  { theme: "Objets", difficulte: "difficile", civil: "Gobelet", imposteur: "Verre" },
  { theme: "Objets", difficulte: "difficile", civil: "Tabouret", imposteur: "Chaise" },
  { theme: "Objets", difficulte: "difficile", civil: "Bocal", imposteur: "Bouteille" },

  // ================= NATURE =================
  { theme: "Nature", difficulte: "facile", civil: "Soleil", imposteur: "Pluie" },
  { theme: "Nature", difficulte: "facile", civil: "Volcan", imposteur: "Lac" },
  { theme: "Nature", difficulte: "facile", civil: "Neige", imposteur: "Sable" },
  { theme: "Nature", difficulte: "facile", civil: "Étoile", imposteur: "Nuage" },
  { theme: "Nature", difficulte: "facile", civil: "Arbre", imposteur: "Rocher" },
  { theme: "Nature", difficulte: "facile", civil: "Vent", imposteur: "Éclair" },
  { theme: "Nature", difficulte: "moyen", civil: "Rivière", imposteur: "Fleuve" },
  { theme: "Nature", difficulte: "moyen", civil: "Colline", imposteur: "Montagne" },
  { theme: "Nature", difficulte: "moyen", civil: "Lac", imposteur: "Étang" },
  { theme: "Nature", difficulte: "moyen", civil: "Forêt", imposteur: "Bois" },
  { theme: "Nature", difficulte: "moyen", civil: "Vague", imposteur: "Marée" },
  { theme: "Nature", difficulte: "moyen", civil: "Nuage", imposteur: "Brouillard" },
  { theme: "Nature", difficulte: "moyen", civil: "Grotte", imposteur: "Caverne" },
  { theme: "Nature", difficulte: "difficile", civil: "Brouillard", imposteur: "Brume" },
  { theme: "Nature", difficulte: "difficile", civil: "Ruisseau", imposteur: "Torrent" },
  { theme: "Nature", difficulte: "difficile", civil: "Averse", imposteur: "Ondée" },

  // ================= TRANSPORTS =================
  { theme: "Transports", difficulte: "facile", civil: "Voiture", imposteur: "Bateau" },
  { theme: "Transports", difficulte: "facile", civil: "Avion", imposteur: "Vélo" },
  { theme: "Transports", difficulte: "facile", civil: "Train", imposteur: "Trottinette" },
  { theme: "Transports", difficulte: "facile", civil: "Fusée", imposteur: "Tracteur" },
  { theme: "Transports", difficulte: "facile", civil: "Métro", imposteur: "Montgolfière" },
  { theme: "Transports", difficulte: "facile", civil: "Camion", imposteur: "Kayak" },
  { theme: "Transports", difficulte: "moyen", civil: "Bus", imposteur: "Tram" },
  { theme: "Transports", difficulte: "moyen", civil: "Moto", imposteur: "Scooter" },
  { theme: "Transports", difficulte: "moyen", civil: "Vélo", imposteur: "Trottinette" },
  { theme: "Transports", difficulte: "moyen", civil: "Train", imposteur: "Métro" },
  { theme: "Transports", difficulte: "moyen", civil: "Bateau", imposteur: "Ferry" },
  { theme: "Transports", difficulte: "moyen", civil: "Camion", imposteur: "Camionnette" },
  { theme: "Transports", difficulte: "moyen", civil: "Taxi", imposteur: "Bus" },
  { theme: "Transports", difficulte: "difficile", civil: "Avion", imposteur: "Hélicoptère" },
  { theme: "Transports", difficulte: "difficile", civil: "Tramway", imposteur: "Trolleybus" },
  { theme: "Transports", difficulte: "difficile", civil: "Voilier", imposteur: "Catamaran" },

  // ================= VÊTEMENTS =================
  { theme: "Vêtements", difficulte: "facile", civil: "Chaussure", imposteur: "Chapeau" },
  { theme: "Vêtements", difficulte: "facile", civil: "Écharpe", imposteur: "Chaussette" },
  { theme: "Vêtements", difficulte: "facile", civil: "Robe", imposteur: "Ceinture" },
  { theme: "Vêtements", difficulte: "facile", civil: "Gant", imposteur: "Cravate" },
  { theme: "Vêtements", difficulte: "facile", civil: "Botte", imposteur: "Casquette" },
  { theme: "Vêtements", difficulte: "moyen", civil: "Pull", imposteur: "Gilet" },
  { theme: "Vêtements", difficulte: "moyen", civil: "Short", imposteur: "Jupe" },
  { theme: "Vêtements", difficulte: "moyen", civil: "Pantalon", imposteur: "Legging" },
  { theme: "Vêtements", difficulte: "moyen", civil: "Manteau", imposteur: "Imperméable" },
  { theme: "Vêtements", difficulte: "moyen", civil: "Baskets", imposteur: "Sandales" },
  { theme: "Vêtements", difficulte: "moyen", civil: "Chemise", imposteur: "Blouse" },
  { theme: "Vêtements", difficulte: "difficile", civil: "Veste", imposteur: "Blazer" },
  { theme: "Vêtements", difficulte: "difficile", civil: "Bonnet", imposteur: "Béret" },
  { theme: "Vêtements", difficulte: "difficile", civil: "Escarpin", imposteur: "Ballerine" },

  // ================= LOISIRS =================
  { theme: "Loisirs", difficulte: "facile", civil: "Lecture", imposteur: "Course à pied" },
  { theme: "Loisirs", difficulte: "facile", civil: "Jardinage", imposteur: "Karaoké" },
  { theme: "Loisirs", difficulte: "facile", civil: "Photographie", imposteur: "Pêche" },
  { theme: "Loisirs", difficulte: "facile", civil: "Tricot", imposteur: "Escalade" },
  { theme: "Loisirs", difficulte: "facile", civil: "Cuisine", imposteur: "Danse" },
  { theme: "Loisirs", difficulte: "facile", civil: "Voyage", imposteur: "Bricolage" },
  { theme: "Loisirs", difficulte: "facile", civil: "Puzzle", imposteur: "Camping" },
  { theme: "Loisirs", difficulte: "moyen", civil: "Cinéma", imposteur: "Théâtre" },
  { theme: "Loisirs", difficulte: "moyen", civil: "Peinture", imposteur: "Dessin" },
  { theme: "Loisirs", difficulte: "moyen", civil: "Guitare", imposteur: "Piano" },
  { theme: "Loisirs", difficulte: "moyen", civil: "Randonnée", imposteur: "Escalade" },
  { theme: "Loisirs", difficulte: "moyen", civil: "Jeux vidéo", imposteur: "Jeux de société" },
  { theme: "Loisirs", difficulte: "moyen", civil: "Chant", imposteur: "Danse" },
  { theme: "Loisirs", difficulte: "moyen", civil: "Sculpture", imposteur: "Poterie" },
  { theme: "Loisirs", difficulte: "difficile", civil: "Échecs", imposteur: "Dames" },
  { theme: "Loisirs", difficulte: "difficile", civil: "Aquarelle", imposteur: "Gouache" },
  { theme: "Loisirs", difficulte: "difficile", civil: "Origami", imposteur: "Scrapbooking" },
  { theme: "Loisirs", difficulte: "difficile", civil: "Belote", imposteur: "Tarot" },
];

// Cle unique d'une paire (pour l'anti-repetition dans une partie).
export function pairKey(pair) {
  return `${pair.civil}|${pair.imposteur}`;
}
